CREATE SEQUENCE A8.SQ_A8_NU_SEQU_REME_PJ
 INCREMENT BY  1
 START WITH  1
 MINVALUE  1
 MAXVALUE  999999999;

/

GRANT SELECT ON A8.SQ_A8_NU_SEQU_REME_PJ TO A8PROC;
GRANT SELECT ON A8.SQ_A8_NU_SEQU_REME_PJ TO RL01_A8_MANUTENCAO;
GRANT SELECT ON A8.SQ_A8_NU_SEQU_REME_PJ TO RL02_A8_CONSULTA;

/
