CREATE SEQUENCE A7.SQ_A7_CO_MESG
 INCREMENT BY 1
 START WITH 1 
 MAXVALUE 1.0E28 
 MINVALUE 1 NOCYCLE 
 CACHE 20 NOORDER;

/

CREATE SEQUENCE A7.SQ_A7_CO_TEXT_XML
 INCREMENT BY 1
 START WITH 1 
 MAXVALUE 1.0E28
 MINVALUE 1 NOCYCLE 
 CACHE 20 NOORDER;

/

GRANT SELECT ON A7.SQ_A7_CO_MESG TO A7PROC;
GRANT SELECT ON A7.SQ_A7_CO_MESG TO RL01_A7_MANUTENCAO;
GRANT SELECT ON A7.SQ_A7_CO_MESG TO RL02_A7_CONSULTA;

/

GRANT SELECT ON A7.SQ_A7_CO_TEXT_XML TO A7PROC;
GRANT SELECT ON A7.SQ_A7_CO_TEXT_XML TO RL01_A7_MANUTENCAO;
GRANT SELECT ON A7.SQ_A7_CO_TEXT_XML TO RL02_A7_CONSULTA;

/

