VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 1  'NoTransaction
END
Attribute VB_Name = "clsBusPublisher"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
'Esta classe tem como objetivo prover a interface para a implementação de classes do tipo "Evento" no COM+.
Option Explicit

'Classe Evento implamentado pela classe BUSSubscriber
Public Sub AcionaGerenciadores(ByVal pstrParametros As String)

'Classe Evento implamentado pela classe BUSSubscriber

End Sub
